"""Seed risk factors for all 117 entries."""
import sqlite3

DB_PATH = "/app/data/scorpio_dna.db"

# Risk factors keyed by rsid + trait
# Format: bullet points, ↑ = increases risk, ↓ = decreases risk
RISK_FACTORS = {
    "rs9939609_Obesity / BMI": "↑ High calorie diet, sedentary lifestyle, processed foods, sleep deprivation\n↑ Stress (raises cortisol which promotes fat storage)\n↓ Regular physical activity (30+ min daily)\n↓ High protein breakfast, fiber-rich diet, mindful eating\n↓ Adequate sleep (7-9 hours)",
    "rs1801133_MTHFR Deficiency": "↑ Low folate intake, smoking, excessive alcohol\n↑ Oral contraceptives (lower folate levels)\n↑ Other B vitamin deficiencies (B6, B12)\n↓ Methylfolate supplementation, folate-rich diet\n↓ Adequate B12, B6, and choline intake",
    "rs7412_Alzheimer's Risk (APOE)": "↓ Protective variant — lower Alzheimer's risk\n↓ Mediterranean diet, regular exercise, mental stimulation\n↓ Good cardiovascular health (heart-healthy = brain-healthy)\n↑ Smoking, high blood pressure, diabetes, head trauma",
    "rs429358_Alzheimer's Risk (APOE)": "↑ Strongest genetic risk factor for late-onset Alzheimer's\n↑ Sedentary lifestyle, poor diet, smoking\n↑ High blood pressure, high cholesterol, diabetes\n↓ Mediterranean/MIND diet, aerobic exercise\n↓ Cognitive stimulation, quality sleep, social engagement",
    "rs1799943_Hemochromatosis (HFE)": "↑ Iron-rich diet, iron supplements, vitamin C megadoses\n↑ Alcohol consumption (increases iron absorption)\n↑ Male sex (women lose iron through menstruation)\n↓ Regular blood donation, avoiding iron supplements\n↓ Chelation therapy if iron overload develops",
    "rs1800562_Hemochromatosis (HFE)": "↑ High penetrance variant — strong genetic driver\n↑ Alcohol, iron supplements, vitamin C supplements\n↑ Red meat-heavy diet, cooking in cast iron\n↓ Regular phlebotomy (blood donation)\n↓ Avoiding iron-fortified foods and supplements",
    "rs328_Lipoprotein(a) / Heart Disease": "↑ Lp(a) is mostly genetically determined — diet barely changes it\n↑ Smoking, sedentary lifestyle, high LDL cholesterol\n↑ Diabetes, high blood pressure\n↓ Niacin, PCSK9 inhibitors (discuss with doctor)\n↓ Aspirin therapy may reduce risk (consult doctor)\n↓ Managing all other cardiovascular risk factors aggressively",
    "rs662799_Triglycerides": "↑ High sugar intake, refined carbohydrates, alcohol\n↑ Sedentary lifestyle, overweight/obesity\n↑ Untreated diabetes, hypothyroidism\n↓ Omega-3 fatty acids (fish oil 2-4g daily)\n↓ Regular aerobic exercise, weight loss\n↓ Low-carb or Mediterranean diet pattern",
    "rs7903146_Type 2 Diabetes": "↑ Overweight/obesity (biggest modifiable risk)\n↑ Sedentary lifestyle, processed food diet\n↑ Sugary drinks, refined carbs, low fiber intake\n↓ Weight loss (5-10% of body weight dramatically reduces risk)\n↓ Regular physical activity (especially after meals)\n↓ High-fiber, low-glycemic diet, strength training",
    "rs5219_Type 2 Diabetes": "↑ Overweight, physical inactivity\n↑ High sugar diet, smoking\n↑ Family history of diabetes\n↓ Healthy weight maintenance\n↓ Post-meal physical activity\n↓ Low-glycemic eating pattern",
    "rs12255372_Type 2 Diabetes": "↑ Same as other T2D variants: obesity, inactivity, poor diet\n↓ Weight management and exercise are highly protective\n↓ Annual HbA1c screening for early detection",
    "rs1800629_TNF-alpha / Inflammation": "↑ Chronic stress, poor sleep, smoking\n↑ High sugar/processed food diet, obesity\n↑ Omega-6 heavy diet (seed oils), lack of exercise\n↓ Omega-3 supplementation, Mediterranean diet\n↓ Regular moderate exercise, stress management\n↓ Adequate sleep (7-9 hours)",
    "rs16944_IL-1B / Inflammation": "↑ Obesity (fat tissue produces inflammatory cytokines)\n↑ Poor sleep, chronic stress, smoking\n↑ High sugar and processed food diet\n↓ Anti-inflammatory diet (berries, greens, fatty fish)\n↓ Regular exercise, good sleep hygiene\n↓ Stress reduction (meditation, nature time)",
    "rs1800795_IL-6 / Inflammation": "↑ Visceral belly fat, smoking, chronic stress\n↑ Sedentary lifestyle, ultra-processed food diet\n↓ Weight loss, regular exercise\n↓ Anti-inflammatory diet, adequate sleep\n↓ Moderate alcohol (if at all) — heavy drinking raises IL-6",
    "rs1801131_MTHFR A1298C": "↑ Low dietary folate, smoking, alcohol\n↑ B12 deficiency, hypothyroidism\n↓ Folate-rich diet (leafy greens, legumes, citrus)\n↓ Methylfolate supplementation if needed\n↓ Adequate B12 and B6 intake",
    "rs1042713_Asthma / ADRB2": "↑ Smoking, air pollution, allergens\n↑ Viral respiratory infections, cold air\n↑ Exercise without proper warm-up\n↓ Avoidance of known triggers\n↓ Proper use of controller medications\n↓ Beta-agonist inhalers (but may be less effective with this variant)",
    "rs1051730_Nicotine Dependence": "↑ Strong genetic predisposition to nicotine addiction\n↑ Early exposure to smoking, peer pressure\n↑ Stress and anxiety (drives smoking behavior)\n↓ Nicotine replacement therapy (patches, gum)\n↓ Prescription cessation aids (varenicline, bupropion)\n↓ Support programs and behavioral counseling",
    "rs16969968_Nicotine Dependence": "↑ Same genetic vulnerability as CHRNA3 variant\n↑ Earlier age of starting smoking increases dependence\n↓ Combination NRT (patch + gum/lozenge)\n↓ Counseling + medication (most effective approach)\n↓ Social support and accountability",
    "rs1544410_Vitamin D / Osteoporosis": "↑ Low sun exposure, northern latitude, dark skin\n↑ Low dietary calcium and vitamin D\n↑ Sedentary lifestyle, smoking, excessive alcohol\n↓ Vitamin D3 supplementation (2000-4000 IU daily)\n↓ Weight-bearing exercise, adequate calcium intake\n↓ Fall prevention: balance training, home safety",
    "rs2228570_Vitamin D / Autoimmunity": "↑ Low vitamin D levels, northern latitude\n↑ Smoking, viral infections (potential triggers)\n↑ Family history of autoimmune disease\n↓ Adequate vitamin D3 supplementation\n↓ Omega-3 fatty acids support immune regulation\n↓ Anti-inflammatory diet, stress management",
    "rs4988235_Lactose Intolerance": "↑ Normal biological pattern for most of the world's population\n↑ Avoiding dairy altogether (missing calcium and vitamin D)\n↓ Lactose-free dairy products\n↓ Lactase enzyme supplements before meals\n↓ Aged cheeses and yogurt (naturally low lactose)",
    "rs182549_Lactose Intolerance": "↑ Same as the LCT variant — this is a second marker\n↓ Lactose-free alternatives widely available\n↓ Enzyme supplements are effective and affordable",
    "rs738409_NAFLD / Fatty Liver": "↑ Strongest genetic risk factor for fatty liver\n↑ High fructose intake (soda, juice, sweets)\n↑ Overweight/obesity, insulin resistance\n↑ Alcohol consumption, sedentary lifestyle\n↓ Weight loss (5-10% significantly reduces liver fat)\n↓ Low sugar diet, exercise (even without weight loss)\n↓ Coffee (2-3 cups daily), Mediterranean diet",
    "rs58542926_NAFLD / Liver Disease": "↑ High sugar/fructose consumption, overweight\n↑ Alcohol, sedentary lifestyle\n↓ Weight management, exercise, low sugar diet\n↓ Coffee consumption (protective for liver)\n↓ Avoiding high-fructose corn syrup",
    "rs2066844_Crohn's Disease / NOD2": "↑ Rare variant — most carriers never develop Crohn's\n↑ Smoking (strong trigger for Crohn's)\n↑ NSAID use, stress, Western diet (high fat, low fiber)\n↓ Mediterranean diet, fiber-rich foods\n↓ Probiotics and fermented foods for gut health",
    "rs2066845_Crohn's Disease / NOD2": "↑ Even rarer variant — very low individual risk\n↑ Smoking is the strongest environmental trigger\n↓ Healthy gut microbiome through diet\n↓ Avoiding unnecessary antibiotics",
    "rs2004640_Autoimmunity / TYK2": "↓ Protective variant — reduced autoimmune risk\n↓ General healthy lifestyle supports immune balance\n↑ No specific risk factors beyond general population baseline",
    "rs1333049_Coronary Artery Disease": "↑ Strongest common genetic risk factor for CAD\n↑ Smoking multiplies the genetic risk dramatically\n↑ High LDL cholesterol, high blood pressure, diabetes\n↑ Sedentary lifestyle, poor diet, obesity\n↓ Statins, blood pressure control, Mediterranean diet\n↓ Regular exercise, no smoking, healthy weight",
    "rs10757278_Heart Attack / CAD": "↑ Same 9p21 locus — heart attack risk variant\n↑ Smoking (critical interaction with this gene)\n↑ Physical inactivity, poor diet, obesity\n↓ Aggressive cardiovascular risk factor management\n↓ Healthy lifestyle largely offsets the genetic risk",
    "rs328_Heart Disease / LPL": "↓ This variant is protective — lower triglycerides, lower heart disease risk\n↓ Even with protection, maintain heart-healthy habits\n↑ General risk factors still apply but baseline is favorable",
    "rs6311_Serotonin / Mood": "↑ Chronic stress, sleep deprivation, lack of sunlight\n↑ Poor diet (low tryptophan, omega-3 deficiency)\n↑ Seasonal changes (especially winter months)\n↓ Regular exercise (one of the best non-drug interventions)\n↓ Morning sunlight exposure, omega-3 supplementation\n↓ Therapy, social connection, consistent sleep schedule",
    "rs6313_Serotonin / Depression": "↑ Seasonal changes (linked to seasonal affective disorder)\n↑ Vitamin D deficiency, lack of sunlight\n↑ Chronic stress, social isolation\n↓ Light therapy during darker months\n↓ Regular exercise, adequate vitamin D\n↓ Consistent sleep-wake schedule",
    "rs4680_COMT / Stress Response": "↑ Caffeine (affects COMT types differently)\n↑ Chronic stress, estrogen fluctuations, sleep deprivation\n↓ For Met (worrier): meditation, magnesium, L-theanine\n↓ For Val (warrior): regular challenges, physical activity\n↓ For both: adequate sleep, balanced diet, stress management",
    "rs6265_BDNF / Memory & Mood": "↑ Sedentary lifestyle (BDNF drops without exercise)\n↑ Chronic stress, poor sleep, social isolation\n↑ High sugar/fat diet, vitamin D deficiency\n↓ Aerobic exercise 3-4x/week (strongest BDNF booster)\n↓ Omega-3s (EPA/DHA), curcumin, blueberries\n↓ Learning new things, quality sleep, social engagement",
    "rs1815739_ACTN3 / Muscle Performance": "↑ XX genotype: reduced fast-twitch muscle fibers\n↓ RR/RX: natural sprint/power advantage\n↓ Training can overcome genetic limitations\n↓ Consistent exercise trumps genetics for most fitness outcomes",
    "rs334_Sickle Cell Anemia": "↑ Having two copies causes sickle cell disease (you have one copy = carrier)\n↑ If both parents are carriers, 25% chance child has disease\n↓ Carrier status alone requires no precautions\n↓ Genetic counseling recommended for family planning\n↓ Some protection against malaria (evolutionary advantage of carrier state)",
    "rs6025_Factor V Leiden": "↑ Estrogen-containing contraceptives/HRT (sharply increases clotting risk)\n↑ Pregnancy, surgery, long immobility (flights, bed rest)\n↑ Smoking, obesity, advanced age\n↓ Avoid estrogen-based birth control\n↓ Stay hydrated and mobile during travel\n↓ Prophylactic blood thinners during high-risk situations",
    "rs1799963_Prothrombin / Clotting": "↑ Same as Factor V Leiden: estrogen, surgery, immobility\n↑ Family history of clots, obesity, smoking\n↓ Avoid estrogen-based contraceptives\n↓ Hydration and movement during long travel\n↓ Medical alert for surgical situations",
    "rs121908001_Cystic Fibrosis (ΔF508)": "↑ If both parents are carriers: 25% CF risk per child\n↑ Most common in European descent populations\n↓ Carrier alone = no health impact\n↓ Partner testing recommended for family planning\n↓ Prenatal testing available if both parents carriers",
    "rs1800078_Cystic Fibrosis (G551D)": "↑ Rarer CF mutation — same carrier implications\n↓ CFTR modulator drugs (ivacaftor) available if both copies affected\n↓ Genetic counseling for family planning",
    "rs1800137_Cystic Fibrosis (W1282X)": "↑ More common in Ashkenazi Jewish populations\n↑ Same carrier implications as other CF mutations\n↓ Genetic counseling for at-risk populations",
    "rs137852587_Tay-Sachs (HEXA)": "↑ Ashkenazi Jewish, French Canadian, Cajun heritage\n↑ If both parents carriers: 25% chance affected child\n↓ Carrier screening widely available\n↓ Prenatal testing options exist for carrier couples\n↓ No health impact on carriers themselves",
    "rs28942079_G6PD Deficiency": "↑ Fava beans (broad beans), certain medications\n↑ Sulfa drugs, aspirin, some antibiotics\n↑ Infections (can trigger hemolytic crisis)\n↓ Avoid known trigger foods and medications\n↓ Check drug interactions before taking new medications\n↓ Most people live normally once triggers are identified",
    "rs1042822_Hemochromatosis (HFE)": "↑ Mild variant — lower penetrance than C282Y\n↑ Iron supplements, alcohol, vitamin C megadoses\n↓ Iron monitoring through annual ferritin testing\n↓ Dietary awareness of iron content",
    "rs28934574_BRCA1 / Breast Cancer": "↑ Ashkenazi Jewish heritage (founder mutation)\n↑ Female sex, early menarche, late menopause\n↑ Hormone replacement therapy, alcohol consumption\n↓ Enhanced screening (MRI + mammogram, starting earlier)\n↓ Risk-reducing surgery, chemoprevention\n↓ Genetic counseling essential",
    "rs80357906_BRCA2 / Breast Cancer": "↑ Same as BRCA1: female sex, Ashkenazi heritage\n↑ Also linked to male breast cancer, pancreatic cancer\n↑ Prostate cancer risk in men\n↓ Enhanced cancer screening\n↓ Genetic counseling and family communication critical",
    "rs1801028_Maple Syrup Urine Disease": "↑ If both parents carriers: 25% risk affected child\n↑ Carrier alone = no health concerns\n↓ Newborn screening catches MSUD early\n↓ Carrier screening available for family planning",
    "rs6443349_Spinal Muscular Atrophy": "↑ ~1 in 50 people carry this — very common\n↑ If both parents carriers: 25% risk affected child\n↓ Recommended as part of standard carrier screening panel\n↓ No impact on carrier's health",
    "rs2071128_Wilson Disease": "↑ Very rare variant\n↑ If both parents carriers: 25% risk affected child\n↓ Carrier alone = no symptoms or precautions\n↓ Genetic counseling for at-risk couples",
    "rs80338902_Gaucher Disease": "↑ Ashkenazi Jewish heritage more common\n↑ If both parents carriers: 25% risk affected child\n↓ Carrier alone = no health impact\n↓ Enzyme replacement therapy exists for affected individuals",
    "rs9923231_Warfarin Sensitivity": "↑ Genetic sensitivity to warfarin — lower doses needed\n↑ Bleeding risk if standard starting dose used\n↑ Other medications that interact with warfarin\n↓ Genetic testing before first dose (done!)\n↓ Alternative anticoagulants (DOACs) available\n↓ Regular INR monitoring",
    "rs1799853_Warfarin Sensitivity": "↑ Reduced warfarin metabolism — higher bleeding risk at standard doses\n↑ Age, liver disease, other medications\n↓ Lower starting dose, close INR monitoring\n↓ DOACs are safer alternatives",
    "rs1057910_Warfarin Sensitivity": "↑ Severely reduced warfarin clearance\n↑ Highest bleeding risk at standard doses\n↓ Lowest starting dose (1-2mg), careful monitoring\n↓ DOACs avoid CYP2C9 metabolism entirely",
    "rs28399433_CYP2A6 / Nicotine Metabolism": "↑ Nicotine stays in system longer — may affect smoking behavior\n↓ May lead to lower cigarette consumption naturally\n↓ Extended nicotine patch therapy may work well\n↓ Bupropion can help with cessation",
    "rs3892097_Codeine Efficacy (CYP2D6)": "↑ Codeine, tramadol, hydrocodone won't work as painkillers\n↑ Post-operative pain may not be controlled with standard meds\n↓ Discuss alternatives: NSAIDs, morphine, hydromorphone\n↓ Non-opioid pain management strategies\n↓ Keep result in medical records",
    "rs3892097_Tamoxifen Metabolism": "↑ Reduced tamoxifen effectiveness for breast cancer treatment\n↑ Higher risk of recurrence if on tamoxifen alone\n↓ Aromatase inhibitors (if postmenopausal) as alternative\n↓ Higher tamoxifen dose may work (discuss with oncologist)\n↓ CYP2D6 testing to confirm metabolizer status",
    "rs1065852_CYP2D6 / Drug Metabolism": "↑ Many medications affected: antidepressants, beta-blockers, opioids\n↑ Risk of side effects from standard doses\n↓ Dose adjustments or alternative medications\n↓ Genetic testing guides medication choices",
    "rs1695_GSTP1 / Chemotherapy": "↑ May affect how well platinum chemotherapy works\n↓ Discuss with oncologist before chemotherapy\n↓ Cruciferous vegetables support natural detox\n↓ No lifestyle changes needed outside of treatment context",
    "rs1042522_TP53 / Chemotherapy": "↑ Minor effect on chemotherapy response\n↑ Smoking, radiation, environmental carcinogens\n↓ Standard cancer prevention: healthy weight, no smoking\n↓ Discuss with oncologist if undergoing chemotherapy",
    "rs1801159_TPMT / Azathioprine": "↑ LIFE-THREATENING: standard azathioprine/6-MP doses cause severe bone marrow suppression\n↑ Fatal if TPMT status unknown before prescribing\n↓ Pre-treatment TPMT testing (already done!)\n↓ Dose reduction to 10-20% of standard\n↓ Alternative medications available (methotrexate, biologics)",
    "rs1800460_TPMT / Thiopurines": "↑ Moderate TPMT deficiency — intermediate risk\n↑ Still need lower starting dose (~30-50% reduction)\n↓ Regular blood count monitoring during treatment\n↓ Safer than *3A/*3C but still requires caution",
    "rs2066853_AHR / Detoxification": "↑ Exposure to environmental toxins (smoke, pollution, pesticides)\n↑ Diet low in cruciferous vegetables\n↓ Eat broccoli, kale, Brussels sprouts, cabbage\n↓ Avoid smoking and excessive alcohol\n↓ Support liver health with adequate hydration",
    "rs762551_Caffeine Metabolism (CYP1A2)": "↓ Fast metabolizers (AA): 3-4 cups coffee daily is safe, even beneficial\n↑ Slow metabolizers (C-carriers): 2+ cups linked to higher heart attack risk\n↑ Slow metabolizers: sleep disruption, anxiety from caffeine\n↓ Slow metabolizers: limit to 1-2 cups before noon",
    "rs776746_CYP3A5 / Drug Metabolism": "↑ No functional CYP3A5 enzyme (affects drug metabolism)\n↑ Tacrolimus requires lower doses (transplant drug)\n↓ Affects many medications — discuss with doctor\n↓ Dose adjustments guided by genetics",
    "rs4149056_Statins / SLCO1B1": "↑ HIGH RISK: simvastatin (Zocor) causes muscle pain/damage\n↑ Risk of rhabdomyolysis with standard simvastatin doses\n↓ Rosuvastatin, pravastatin, or low-dose atorvastatin safer\n↓ Discuss statin choice with doctor\n↓ Muscle symptoms on any statin should be reported immediately",
    "rs12248560_CYP2C19 / Clopidogrel": "↓ Better clopidogrel activation = better clot prevention\n↑ Higher bleeding risk — may need to pause before surgery\n↑ Watch for unusual bruising\n↓ Effective antiplatelet protection for stents",
    "rs4244285_CYP2C19 / Clopidogrel": "↑ CRITICAL: clopidogrel does NOT work — no antiplatelet effect\n↑ High risk of stent thrombosis if relying on clopidogrel\n↓ Switch to ticagrelor (Brilinta) or prasugrel (Effient)\n↓ Must inform ALL doctors (GP, cardiologist, ER) about this\n↓ Keep result in wallet or medical ID",
    "rs4986893_CYP2C19 / Clopidogrel": "↑ Same as *2 variant — clopidogrel ineffective\n↑ More common in East Asian populations\n↓ Alternative antiplatelet therapy required\n↓ Important for heart stent patients",
    "rs7495174_Eye Color": "↑ No health risk factors — this is a cosmetic trait\n↓ Light eye color may mean slightly more light sensitivity\n↓ Not a medical concern in any way",
    "rs12913832_Eye Color (Blue/Brown)": "↑ No health risk — physical trait only\n↓ Light eyes may benefit from UV-protective sunglasses",
    "rs1805007_Hair Color (Red)": "↑ Sun exposure burns easily — high skin cancer risk\n↑ UV radiation from sun or tanning beds\n↑ Anesthesia sensitivity — discuss before surgery\n↓ Daily SPF 30+, sun-protective clothing\n↓ Annual dermatology skin checks\n↓ Vitamin D from supplements (skin makes less)",
    "rs1805008_Hair Color (Red)": "↑ Same MC1R-related risks: sun sensitivity, skin cancer\n↑ May need higher anesthesia doses\n↓ SPF daily, avoid sunburns, regular skin checks",
    "rs1805009_Hair Color (Red)": "↑ Same sun and anesthesia considerations\n↓ Annual skin checks, daily sun protection",
    "rs17822931_Earwax Type": "↑ No health risk factors — harmless physical trait\n↓ Both earwax types are normal and healthy\n↓ Don't clean ear canal with cotton swabs (risks damage)",
    "rs3827760_Hair Thickness": "↑ No health concerns — normal genetic variation\n↓ Affects hair texture, tooth shape, and sweat glands\n↓ All variations are healthy",
    "rs16891982_Skin Pigmentation": "↑ Fair skin burns more easily in sun\n↑ Higher skin cancer risk with low melanin\n↓ Daily SPF 30+, avoid peak sun hours\n↓ Annual skin checks with a dermatologist\n↓ No tanning beds",
    "rs1426654_Skin Pigmentation": "↑ Same skin cancer risk as other light-skin variants\n↓ Sun protection and regular skin checks\n↓ Vitamin D supplementation may be needed with strict sun avoidance",
    "rs4988235_Lactose Tolerance": "↓ Lactose persistence is an advantage for dairy consumption\n↓ Good calcium source — supports bone health\n↑ No health risks from the trait itself\n↑ Dairy intolerance possible from other causes (not LCT)",
    "rs621922_Freckles": "↑ Freckles indicate sun-sensitive skin\n↑ Sun exposure worsens freckling and raises skin cancer risk\n↓ SPF 30+ daily, avoid tanning\n↓ Regular skin checks if many moles or fair skin",
    "rs10756819_Male Pattern Baldness": "↑ Higher androgen levels (also means lower prostate cancer risk)\n↑ Stress, smoking, poor diet can accelerate hair loss\n↓ Treatments: finasteride, minoxidil, LLLT\n↓ Starting treatment early gives best results",
    "rs2180439_Male Pattern Baldness": "↑ Same as other baldness variants\n↑ Early onset more likely with multiple variants\n↓ Combination treatment (finasteride + minoxidil) most effective",
    "rs28777_Hair Type (Straight/Curly)": "↑ No health risk — normal trait variation\n↓ Hair type is purely cosmetic and genetic",
    "rs11803731_Hair Graying": "↑ Premature graying caused by this gene\n↑ Rarely associated with B12 or copper deficiency if very early onset\n↓ No treatment needed — gray hair is normal\n↓ If graying before 20, check B12 levels",
    "rs1801133_Folate Metabolism": "↑ Low folate intake, smoking, alcohol, oral contraceptives\n↑ Pregnancy (increased folate needs)\n↓ Methylfolate supplementation (400-800 mcg daily)\n↓ Folate-rich diet (leafy greens, legumes, citrus)\n↓ Crucial before and during pregnancy",
    "rs1801131_Folate Metabolism (A1298C)": "↑ Same as C677T but milder effect\n↑ Low dietary folate, smoking, alcohol\n↓ Methylfolate supplementation\n↓ Folate-rich foods in diet",
    "rs762551_Caffeine Metabolism": "↓ Fast metabolizers: no risk from coffee, even protective\n↑ Slow metabolizers: 2+ cups raise heart attack risk\n↑ Slow metabolizers: anxiety, insomnia from caffeine\n↓ Slow metabolizers: switch to decaf, limit intake",
    "rs705381_Vitamin B12 Levels": "↑ Low dietary B12 (vegans, vegetarians at risk)\n↑ PPIs and antacids (reduce B12 absorption)\n↑ Age (absorption decreases after 50)\n↓ B12-rich foods: meat, fish, eggs, dairy\n↓ Sublingual B12 supplements if levels low\n↓ Annual B12 testing",
    "rs2297518_Vitamin A / Iron": "↑ Poor diet lacking in vitamin A and iron sources\n↑ Absorption issues from gut conditions\n↓ Balanced diet with vitamin A (sweet potato, carrots, leafy greens) and iron (meat, legumes, spinach)\n↓ Testing if deficiency symptoms appear",
    "rs3750941_Iron Status": "↑ Iron supplements (don't take unless deficient)\n↑ Red meat-heavy diet may push iron higher\n↓ Regular blood donation helps maintain healthy levels\n↓ Annual ferritin monitoring\n↓ Avoid iron-fortified foods if levels high",
    "rs602662_Vitamin B12 Status": "↓ This variant is favorable — higher B12 levels\n↓ No special risk factors\n↓ Maintain B12 through diet or supplements as needed",
    "rs12794714_Vitamin D Metabolism": "↑ Low sun exposure, northern latitude, dark skin\n↑ Obesity (sequesters vitamin D in fat)\n↑ Aging (reduced skin synthesis)\n↓ Vitamin D3 supplementation (2000-5000 IU)\n↓ 15 min midday sun on arms/face when possible\n↓ Fatty fish, egg yolks, fortified foods",
    "rs1993116_Saturated Fat Sensitivity": "↑ Saturated fat intake (butter, fatty meats, fried foods)\n↑ Overweight, sedentary lifestyle\n↓ Replace saturated fats with unsaturated (olive oil, avocado, nuts)\n↓ Mediterranean diet pattern\n↓ Regular physical activity",
    "rs1535_Fatty Acid Metabolism": "↓ Favorable variant — efficient omega-3 conversion\n↑ Low intake of omega-3 sources (flax, walnuts, chia, fish)\n↑ High omega-6 intake (seed oils) unbalances ratio\n↓ Include plant omega-3s regularly\n↓ Consider fish oil for EPA/DHA",
    "rs174547_Omega-3 / Omega-6 Balance": "↑ High omega-6 diet (processed foods, vegetable oils)\n↑ Low fish intake, lack of omega-3 sources\n↓ Increase fatty fish or fish oil supplementation\n↓ Reduce processed foods with seed oils\n↓ Eat flax, chia, walnuts for ALA",
    "rs1784753_Sodium Sensitivity": "↑ High sodium diet, processed foods, restaurant meals\n↑ Low potassium intake (not enough fruits/vegetables)\n↓ Reduce added salt, cook from whole foods\n↓ Eat potassium-rich foods (bananas, potatoes, greens)\n↓ Monitor blood pressure regularly",
    "rs5186_Salt / Blood Pressure": "↑ High salt intake, processed food diet\n↑ Low potassium, magnesium, calcium intake\n↑ Obesity, sedentary lifestyle, alcohol, smoking\n↓ DASH diet (rich in produce, low-fat dairy, whole grains)\n↓ Regular aerobic exercise\n↓ Blood pressure monitoring",
    "rs1799752_ACE / Blood Pressure": "↑ D-allele = higher ACE activity = tighter blood vessels\n↑ High sodium diet, obesity, sedentary lifestyle\n↓ Aerobic exercise (particularly effective for this variant)\n↓ DASH diet, sodium reduction\n↓ ACE inhibitors may be especially effective if hypertension develops",
    "rs1815739_ACTN3 / Sprint Performance": "↑ XX genotype: no alpha-actinin-3 (sprint disadvantage)\n↓ RR/RX: natural sprint/power advantage\n↓ Training can significantly improve performance regardless\n↓ Sport choice may align with natural tendency but isn't limiting",
    "rs8192678_Aerobic Fitness / PPARGC1A": "↑ May require more training to achieve same aerobic gains\n↑ Sedentary lifestyle minimizes your aerobic potential\n↓ Consistency in endurance training is key\n↓ HIIT may help overcome this genetic limitation\n↓ Don't compare progress to fast responders — everyone improves differently",
    "rs4253778_PPARA / Endurance": "↓ Favorable variant for endurance performance\n↓ Regular endurance training will show good results\n↓ Your body uses fat efficiently during exercise\n↑ Sedentary lifestyle wastes this genetic advantage",
    "rs1800795_IL-6 / Recovery": "↓ Potentially better exercise recovery\n↓ May tolerate higher training volumes\n↑ Overtraining still possible — respect recovery days\n↑ Poor sleep and nutrition negate recovery advantages",
    "rs4646994_ACE / Endurance vs Power": "↓ I-allele: endurance advantage — enjoy distance activities\n↓ D-allele: power/sprint advantage — strength and speed activities\n↑ Neither type limits you — train for what you enjoy\n↓ Both types benefit from balanced training programs",
    "rs3764675_Muscle Mass / MSTN": "↓ Slight muscle-building advantage with this variant\n↓ Consistent strength training maximizes potential\n↑ Poor protein intake, inadequate recovery limits gains\n↓ Adequate protein (1.6-2.2g per kg bodyweight) supports muscle growth",
    "rs1805086_VO2 Max / VEGFR2": "↓ Good aerobic response to training\n↓ Consistent endurance training improves VO2 max\n↑ Sedentary lifestyle = no advantage realized\n↓ HIIT sessions boost VO2 max efficiently",
    "rs1049434_Lactate / MCT1": "↑ May fatigue faster during high intensity exercise\n↑ Poor pacing leads to early lactate accumulation\n↓ Training improves lactate clearance over time\n↓ Proper warm-up and pacing strategies help\n↓ Interval training with adequate recovery",
    "rs2014355_Injury Risk / COL5A1": "↑ Higher Achilles tendon injury risk\n↑ Sudden increases in training intensity or volume\n↑ Running on hard surfaces, improper footwear\n↓ Eccentric heel drop exercises strengthen Achilles\n↓ Progressive training load, adequate warm-up\n↓ Listen to early tendon pain — rest before it becomes an injury",
    "rs12722_Tendon Injury / COL5A1": "↓ Protective variant — lower tendon injury risk\n↓ Maintain good training habits regardless\n↓ Strengthening still important for long-term health",
    "rs4680_COMT / Worrier vs Warrior": "↑ For Met (worrier): caffeine, stress, lack of sleep hit harder\n↑ For Val (warrior): may miss body signals, higher risk tolerance\n↓ For both: adequate sleep, balanced nutrition, stress management\n↓ Neither type is better — different environments favor different types",
    "rs6311_Anxiety / HTR2A": "↑ Chronic stress, caffeine excess, sleep deprivation\n↑ Negative thought patterns, social isolation\n↓ Regular exercise, morning sunlight, mindfulness\n↓ Therapy (CBT is evidence-based for anxiety)\n↓ Limiting caffeine and alcohol",
    "rs25531_SERT / Stress Sensitivity": "↑ Childhood adversity, chronic stress, poor social support\n↑ Sleep deprivation, poor nutrition\n↓ Strong social connections are EXTRA protective for short allele carriers\n↓ Exercise, therapy, mindfulness\n↓ Supportive environments matter more for this variant",
    "rs6265_BDNF / Neuroticism": "↑ Sedentary lifestyle (BDNF drops without exercise)\n↑ Chronic stress, poor sleep, social isolation\n↑ High sugar/fat diet\n↓ Aerobic exercise is the best non-drug intervention\n↓ Novel experiences and learning boost BDNF\n↓ Omega-3s, quality sleep, social connection",
    "rs6313_HTR2A / Personality": "↑ Seasonal changes, lack of sunlight\n↑ Chronic stress, social isolation\n↓ Light therapy, regular outdoor time\n↓ Consistent sleep schedule, exercise\n↓ Therapy or counseling if mood symptoms interfere with daily life",
    "rs1800497_DRD2 / Reward Seeking": "↑ Fewer D2 receptors = higher addiction vulnerability\n↑ Higher risk: smoking, alcohol, gambling, drugs, social media addiction\n↓ Exercise provides healthy dopamine — make it a habit\n↓ Be mindful of reward-seeking behaviors\n↓ Dopamine detox (reducing high-stimulation activities) helps reset sensitivity",
    "rs1611115_DBH / Norepinephrine": "↑ May affect attention regulation\n↑ Chronic stress, poor sleep, nutritional deficiencies\n↓ Adequate protein intake (tyrosine supports norepinephrine production)\n↓ Exercise, good sleep, stress management\n↓ If attention issues severe, discuss with doctor",
    "rs53576_OXTR / Empathy & Social": "↓ G-allele: higher empathy, trust, social bonding\n↑ A-allele: more independent, less affected by social dynamics\n↓ Social connection benefits both types — find what works for you\n↓ G-allele individuals may need to protect against social burnout\n↓ A-allele individuals may need to consciously invest in relationships",
    "rs5443_GNB3 / Mood": "↑ T-allele linked to higher anxiety/depression risk\n↑ Chronic stress, sleep deprivation, poor nutrition\n↓ Regular exercise, adequate sleep, stress management\n↓ May respond differently to antidepressants — discuss with doctor\n↓ Therapy (CBT, DBT) effective regardless of genetics",
    "rs324981_TAS2R38 / Bitter Taste": "↑ Supertasters may dislike vegetables (health concern via diet quality)\n↑ Non-tasters may consume more alcohol (can't taste bitterness)\n↑ Supertasters: roast veggies to reduce bitterness, add healthy fats\n↑ Non-tasters: be mindful of alcohol intake\n↓ Both types can achieve healthy diets knowing their taste tendency",
}

conn = sqlite3.connect(DB_PATH)
c = conn.cursor()

# Check for missing
c.execute("SELECT rsid, trait FROM reference_snps")
existing = {(r[0], r[1]) for r in c.fetchall()}
rf_keys = set()
for k in RISK_FACTORS:
    parts = k.split("_", 1)
    rf_keys.add((parts[0], parts[1] if len(parts) > 1 else ""))

missing = rf_keys - existing
extra = existing - rf_keys
if missing:
    print(f"WARNING: {len(missing)} risk factor entries missing from DB:")
    for r in missing:
        print(f"  {r[0]} - {r[1]}")
if extra:
    print(f"WARNING: {len(extra)} DB entries missing risk factors:")
    for r in extra:
        print(f"  {r[0]} - {r[1]}")

# Update DB
updated = 0
for key, rf in RISK_FACTORS.items():
    parts = key.split("_", 1)
    rsid = parts[0]
    trait = parts[1] if len(parts) > 1 else ""
    c.execute("UPDATE reference_snps SET risk_factors = ? WHERE rsid = ? AND trait = ?", (rf, rsid, trait))
    if c.rowcount > 0:
        updated += 1

conn.commit()
print(f"\nUpdated {updated} of {len(RISK_FACTORS)} entries with risk factors")
conn.close()
