"""Seed health tips for all 117 entries."""
import sqlite3

DB_PATH = "/app/data/scorpio_dna.db"

# Practical, actionable health tips keyed by rsid + trait
TIPS = {
    "rs9939609_Obesity / BMI": "• Focus on whole foods, fiber-rich meals (veggies, legumes) to feel full on fewer calories\n• Regular physical activity (30min+ daily) helps counteract genetic tendency\n• Track portion sizes — your body may not signal fullness as effectively\n• Prioritize protein at breakfast to stabilize appetite throughout the day",
    "rs1801133_MTHFR Deficiency": "• Take methylfolate (active folate) instead of regular folic acid supplements\n• Eat folate-rich foods: leafy greens, asparagus, lentils, avocado\n• Avoid excessive alcohol — it raises homocysteine further\n• Consider B12 and B6 supplements alongside methylfolate for complete homocysteine support",
    "rs7412_Alzheimer's Risk (APOE)": "• Maintain a brain-healthy lifestyle: Mediterranean diet, regular exercise, social engagement\n• Keep blood pressure, cholesterol, and blood sugar in healthy ranges\n• Stay mentally active: reading, puzzles, learning new skills\n• This is a protective variant — your genetic baseline is favorable",
    "rs429358_Alzheimer's Risk (APOE)": "• Follow a Mediterranean or MIND diet rich in berries, leafy greens, fish, and olive oil\n• Exercise regularly (aerobic + strength training) — one of the strongest lifestyle protectors\n• Keep blood pressure, cholesterol, and blood sugar tightly controlled\n• Prioritize quality sleep (7-9 hours) — helps clear brain waste products\n• Stay socially engaged and mentally active\n• This is a risk factor, not a diagnosis — lifestyle matters enormously",
    "rs1799943_Hemochromatosis (HFE)": "• Avoid iron supplements and multivitamins with iron unless blood tests confirm deficiency\n• Limit vitamin C supplements (enhances iron absorption)\n• Donate blood regularly if ferritin levels are elevated\n• Avoid raw shellfish (carry bacteria that can cause serious infections in iron-loaded individuals)\n• Test ferritin and iron saturation annually",
    "rs1800562_Hemochromatosis (HFE)": "• Have ferritin and iron saturation tested annually\n• Donate blood every 2-3 months if iron levels are high — therapeutic phlebotomy is the treatment\n• Avoid iron supplements, vitamin C megadoses, and raw shellfish\n• Limit alcohol intake (especially red wine, which is high in iron)\n• Cook in stainless steel instead of cast iron pans",
    "rs328_Lipoprotein(a) / Heart Disease": "• Get Lp(a) blood test — it's not part of standard cholesterol panels\n• Optimize everything you can control: LDL cholesterol, blood pressure, diet, exercise\n• Niacin and PCSK9 inhibitors can lower Lp(a) — discuss with your doctor\n• Mediterranean diet and regular exercise help reduce overall cardiovascular risk\n• Avoid trans fats and limit saturated fats",
    "rs662799_Triglycerides": "• Cut back on sugar and refined carbs (white bread, pasta, sweets)\n• Eat fatty fish (salmon, mackerel, sardines) 2-3 times per week or take omega-3 supplements\n• Regular aerobic exercise is highly effective at lowering triglycerides\n• Limit alcohol — even moderate amounts raise triglycerides significantly\n• Maintain a healthy weight",
    "rs7903146_Type 2 Diabetes": "• Keep your weight in a healthy range — this is the single most impactful factor\n• Walk 15-20 minutes after meals — helps control blood sugar spikes\n• Eat a low-glycemic diet: focus on fiber, protein, healthy fats; limit sugar and refined carbs\n• Get tested for HbA1c annually to catch any elevation early\n• Strength training 2x/week improves insulin sensitivity more than cardio alone",
    "rs5219_Type 2 Diabetes": "• Same as general diabetes prevention: healthy weight, active lifestyle, low glycemic diet\n• This gene affects insulin secretion — eating smaller, more frequent meals may help\n• Exercise after meals to help your pancreas with glucose clearance\n• Monitor HbA1c yearly",
    "rs12255372_Type 2 Diabetes": "• Same lifestyle recommendations as the main T2D variant\n• Weight management and exercise are the strongest protective factors\n• Annual HbA1c screening recommended",
    "rs1800629_TNF-alpha / Inflammation": "• Eat an anti-inflammatory diet: fatty fish, berries, turmeric, ginger, olive oil\n• Reduce processed foods, sugar, and seed oils (soybean, corn, sunflower)\n• Regular moderate exercise lowers TNF-alpha levels\n• Manage stress — chronic stress keeps inflammation high\n• Consider omega-3 supplements (2-3g EPA/DHA daily)",
    "rs16944_IL-1B / Inflammation": "• Follow an anti-inflammatory diet pattern (Mediterranean diet is well-studied)\n• Get quality sleep — poor sleep raises IL-1β levels\n• Limit alcohol and avoid smoking\n• Regular exercise, but don't overtrain — extreme exercise can temporarily increase inflammation",
    "rs1800795_IL-6 / Inflammation": "• Anti-inflammatory diet rich in omega-3s (fish, walnuts, flaxseeds)\n• Moderate exercise reduces IL-6 long-term\n• Maintain healthy body weight — fat tissue produces inflammatory cytokines\n• Manage chronic stress through meditation, nature walks, or therapy",
    "rs1801131_MTHFR A1298C": "• Consider methylfolate supplements if you have symptoms or elevated homocysteine\n• Eat folate-rich foods: dark leafy greens, beans, citrus, beets\n• If you also carry the C677T variant (compound heterozygote), treat it like two copies of C677T\n• Ask your doctor to test homocysteine levels",
    "rs1042713_Asthma / ADRB2": "• If you have asthma, discuss your albuterol response with your doctor\n• Know your triggers and have an action plan\n• Consider a written asthma management plan from your pulmonologist\n• Genetic testing can guide medication choices — bring this up with your doctor",
    "rs1051730_Nicotine Dependence": "• If you smoke, consider nicotine replacement therapy (patches, gum) — it may work better than cold turkey\n• Varenicline (Chantix) and bupropion can help reduce cravings\n• Your brain chemistry makes quitting harder, not a willpower failure\n• Enroll in a smoking cessation program for support",
    "rs16969968_Nicotine Dependence": "• Same approach as above — nicotine addiction is biologically harder for you\n• Combination NRT (patch + gum/lozenge) may be more effective\n• Talk to your doctor about prescription cessation aids\n• Don't blame yourself if quitting is difficult — your genetics are working against you",
    "rs1544410_Vitamin D / Osteoporosis": "• Get your vitamin D levels tested — aim for 50-80 ng/mL\n• Take 2000-4000 IU vitamin D3 daily (with vitamin K2 for calcium routing)\n• Ensure adequate calcium intake (dairy, leafy greens, fortified foods)\n• Weight-bearing exercise (walking, jogging, strength training) to maintain bone density\n• Consider a DEXA bone density scan if over 50 or at risk",
    "rs2228570_Vitamin D / Autoimmunity": "• Test vitamin D levels and keep them in optimal range (50-80 ng/mL)\n• Take vitamin D3 daily (2000-5000 IU depending on levels)\n• Also consider omega-3s — they synergize with vitamin D for immune regulation\n• Watch for autoimmune symptoms and discuss with your doctor if they appear",
    "rs4988235_Lactose Intolerance": "• Use lactose-free milk and dairy products — same nutrition without the discomfort\n• Take lactase enzyme pills before eating dairy (available over the counter)\n• Aged cheeses (cheddar, parmesan, Swiss) are naturally low in lactose\n• Yogurt with live cultures is often well-tolerated\n• Get calcium from alternative sources if avoiding dairy: fortified plant milks, leafy greens, almonds",
    "rs182549_Lactose Intolerance": "• Same advice as above — this is another marker for the same trait\n• Lactose intolerance is normal (most adults worldwide have it), not a health problem",
    "rs738409_NAFLD / Fatty Liver": "• Cut added sugar drastically — especially sugary drinks and fruit juice (fructose drives liver fat)\n• Reduce or eliminate alcohol\n• Lose weight if overweight — even 5-10% loss significantly reduces liver fat\n• Exercise helps reduce liver fat independent of weight loss\n• Coffee (2-3 cups daily) is associated with less liver fat — keep it black or with minimal sugar",
    "rs58542926_NAFLD / Liver Disease": "• Same liver-friendly advice as above\n• Avoid high-fructose corn syrup and excess alcohol\n• Maintain healthy weight and exercise regularly\n• Get liver enzymes tested (ALT, AST) annually",
    "rs2066844_Crohn's Disease / NOD2": "• This is a rare variant — most carriers never develop Crohn's\n• If you have digestive symptoms (chronic diarrhea, abdominal pain), see a gastroenterologist\n• An anti-inflammatory diet may help reduce gut inflammation\n• Probiotics and fermented foods support gut microbiome health",
    "rs2066845_Crohn's Disease / NOD2": "• Same advice as above — very rare, low individual risk\n• Listen to your gut: any persistent digestive symptoms warrant a checkup",
    "rs2004640_Autoimmunity / TYK2": "• This variant is actually protective — your immune signaling is more regulated\n• Maintain general health habits: good sleep, balanced nutrition, stress management\n• No special precautions needed beyond general wellness",
    "rs1333049_Coronary Artery Disease": "• Get a coronary calcium scan (CAC) in your 40s or earlier if other risk factors present\n• Keep LDL cholesterol below 100 mg/dL (or below 70 if high risk)\n• Exercise 150+ minutes per week of moderate activity\n• Mediterranean diet is specifically proven to reduce heart disease risk\n• Know your blood pressure and keep it below 120/80\n• Don't smoke — especially impactful with this variant",
    "rs10757278_Heart Attack / CAD": "• Same advice as the 9p21 variant above\n• Heart health basics matter extra for you: don't smoke, exercise, healthy weight, manage stress\n• Discuss with your doctor whether a statin or baby aspirin is appropriate for prevention",
    "rs328_Heart Disease / LPL": "• This variant is beneficial — it helps you process blood fats efficiently\n• You have a genetic advantage for heart health\n• Still follow general heart-healthy guidelines, but you're starting from a good place",
    "rs6311_Serotonin / Mood": "• If you struggle with mood, know that SSRI antidepressants may work differently for you\n• Exercise, sunlight exposure, and omega-3s naturally support serotonin function\n• Monitor your mood seasonally — this variant links to seasonal patterns\n• Consider therapy or counseling as proactive mental health support",
    "rs6313_Serotonin / Depression": "• Track your mood changes across seasons — this variant is linked to seasonal patterns\n• Light therapy in darker months may be especially helpful for you\n• If prescribed antidepressants, discuss that you may process SSRIs differently\n• Regular exercise, sleep schedule, and morning sunlight help stabilize mood",
    "rs4680_COMT / Stress Response": "• If you have the Met (A) version: you may feel stress more intensely but focus better under pressure — use mindfulness and relaxation techniques proactively\n• If you have the Val (G) version: you handle stress well but may miss subtle emotional cues — practice checking in with your feelings\n• The Worrier type benefits from: meditation, adequate sleep, magnesium supplements\n• The Warrior type benefits from: seeking novel challenges, pushing comfort zones, getting enough stimulation",
    "rs6265_BDNF / Memory & Mood": "• Aerobic exercise (running, cycling, brisk walking) 3-4x/week boosts BDNF naturally\n• High-intensity interval training (HIIT) may increase BDNF more than steady-state cardio\n• Omega-3 fatty acids (EPA/DHA) support BDNF production\n• Curcumin (turmeric) and flavonoids (blueberries, dark chocolate) may also increase BDNF\n• Quality sleep is essential for BDNF-dependent memory consolidation\n• Learn new things regularly — novel experiences stimulate BDNF",
    "rs1815739_ACTN3 / Muscle Performance": "• If you have the power version (RR/RX): you may excel at sprinting, jumping, strength sports\n• If you have the endurance version (XX): you may excel at distance running, cycling, endurance activities\n• Don't let this limit you — train for your goals regardless of genetics\n• XX individuals: strength training still works well, just with a different fiber-type composition",
    "rs334_Sickle Cell Anemia": "• You are a carrier only — you do not have sickle cell disease\n• No health precautions needed for you personally\n• If planning children, have your partner tested — if both carriers, there's a 25% chance per pregnancy of the child having sickle cell disease\n• Genetic counseling is recommended for family planning",
    "rs6025_Factor V Leiden": "• Inform your doctor about this before surgery, pregnancy, or hospital stays\n• On long flights (4+ hours): walk every hour, stay hydrated, consider compression stockings\n• Avoid estrogen-containing birth control (pills, patches) — they sharply increase clotting risk\n• Stay well hydrated and mobile during long car or plane trips\n• Consider discussing with your doctor whether you need prophylactic blood thinners during high-risk situations",
    "rs1799963_Prothrombin / Clotting": "• Same precautions as Factor V Leiden\n• Inform doctors before surgery or hospitalization\n• Avoid estrogen-based contraceptives\n• Stay hydrated and mobile during long flights\n• Discuss family planning implications with your doctor if relevant",
    "rs121908001_Cystic Fibrosis (ΔF508)": "• You are a carrier — you have no symptoms and need no treatment\n• If planning children, have your partner tested for CF mutations\n• ~1 in 25 people of European descent carry a CF mutation\n• Genetic counseling can explain the risks",
    "rs1800078_Cystic Fibrosis (G551D)": "• Same carrier guidance as above\n• If you or a family member has CF symptoms, this mutation is responsive to ivacaftor (Kalydeco), a targeted therapy",
    "rs1800137_Cystic Fibrosis (W1282X)": "• Same carrier guidance\n• More common in Ashkenazi Jewish populations — relevant for ancestry-based carrier screening",
    "rs137852587_Tay-Sachs (HEXA)": "• Carrier status only — no health impact on you\n• If planning children and both partners are of Ashkenazi Jewish descent, carrier screening is recommended\n• Genetic counseling is standard for family planning with known carrier status",
    "rs28942079_G6PD Deficiency": "• Avoid known triggers: fava beans, certain medications (sulfa antibiotics, primaquine, some painkillers)\n• Check medications with your doctor or pharmacist before taking new prescriptions\n• Be cautious with certain herbal supplements and naphthalene (mothballs)\n• Most people with G6PD deficiency live completely normally once they know their triggers",
    "rs1042822_Hemochromatosis (HFE)": "• Milder variant — monitoring is less critical than with C282Y\n• Still avoid unnecessary iron supplements\n• Test ferritin once to establish your baseline, then check again if symptoms develop",
    "rs28934574_BRCA1 / Breast Cancer": "• Seek genetic counseling from a certified genetic counselor\n• Discuss enhanced screening: mammograms starting earlier, breast MRI, clinical breast exams\n• Talk to your doctor about risk-reducing medications or surgeries\n• This affects more than breast cancer — discuss ovarian, pancreatic, and prostate cancer screening too\n• Inform family members — they may also carry this mutation\n• Lifestyle factors (weight, exercise, alcohol limitation) also influence risk",
    "rs80357906_BRCA2 / Breast Cancer": "• Same as BRCA1 — seek genetic counseling\n• Enhanced screening for breast, ovarian, pancreatic, and prostate cancers\n• BRCA2 is also linked to male breast cancer — important for all family members\n• Discuss risk-reduction options with a specialist",
    "rs1801028_Maple Syrup Urine Disease": "• Carrier only — you have no symptoms\n• Relevant only for family planning with another carrier\n• Newborn screening in most countries catches MSUD early if it occurs",
    "rs6443349_Spinal Muscular Atrophy": "• Carrier only — no symptoms or precautions needed\n• ~1 in 50 people carry this — it's common\n• If planning children, partner testing and genetic counseling recommended",
    "rs2071128_Wilson Disease": "• Carrier only — no precautions needed for you\n• Only relevant if your partner is also a carrier (very rare)\n• Newborn screening is available in many regions",
    "rs80338902_Gaucher Disease": "• Carrier only — no health impact\n• Most common in Ashkenazi Jewish populations\n• If planning children, carrier screening and genetic counseling recommended",
    "rs9923231_Warfarin Sensitivity": "• TELL YOUR DOCTOR about this variant if prescribed warfarin (Coumadin)\n• You will likely need a significantly lower starting dose (2-3mg vs 5mg standard)\n• Expect more frequent INR monitoring during dose adjustment\n• Consider newer anticoagulants (apixaban, rivaroxaban) that don't need genetic dosing",
    "rs1799853_Warfarin Sensitivity": "• Inform your doctor before starting warfarin\n• Reduced CYP2C9 activity means slower warfarin clearance — lower doses needed\n• Discuss alternatives like DOACs (apixaban, edoxaban) which don't have CYP2C9 interactions",
    "rs1057910_Warfarin Sensitivity": "• Significantly reduced warfarin metabolism — your doctor needs to know before prescribing\n• Starting dose may need to be as low as 1-2mg daily\n• DOACs are a safer alternative that bypass CYP2C9 metabolism entirely",
    "rs28399433_CYP2A6 / Nicotine Metabolism": "• Nicotine stays in your system longer — patches may work better than faster-acting NRT\n• You may smoke fewer cigarettes naturally due to slower nicotine clearance\n• If trying to quit, extended therapy (step-down approach) may suit your metabolism better",
    "rs3892097_Codeine Efficacy (CYP2D6)": "• Codeine, tramadol, and hydrocodone WON'T WORK as pain relievers for you\n• Your body can't convert them into their active form\n• Ask your doctor about alternatives: NSAIDs, morphine, hydromorphone, or non-opioid options\n• Keep this result in your medical records — it's relevant for ER visits too",
    "rs3892097_Tamoxifen Metabolism": "• If you're prescribed tamoxifen for breast cancer prevention or treatment, this result matters\n• Your body can't convert tamoxifen into its active metabolite (endoxifen)\n• Ask your doctor about aromatase inhibitors (if postmenopausal) or high-dose tamoxifen\n• Consider a CYP2D6 phenotype test to confirm your metabolizer status",
    "rs1065852_CYP2D6 / Drug Metabolism": "• Your CYP2D6 enzyme works at reduced capacity — this affects many common drugs\n• Medications most affected: antidepressants (fluoxetine, paroxetine), antipsychotics, beta-blockers (metoprolol), opioids (codeine, tramadol)\n• Your doctor may need to adjust doses or choose alternative medications\n• Keep this result in your medical records",
    "rs1695_GSTP1 / Chemotherapy": "• If undergoing chemotherapy, your oncologist should know about your GSTP1 status\n• May affect how well certain platinum-based drugs (cisplatin, carboplatin) work\n• Discuss with your oncologist whether dose adjustment is needed\n• Broccoli, cauliflower, and other cruciferous vegetables support your body's natural detox pathways",
    "rs1042522_TP53 / Chemotherapy": "• This minor variant has limited clinical impact on its own\n• Discuss with your oncologist if undergoing chemotherapy\n• General cancer prevention: avoid smoking, limit alcohol, maintain healthy weight, stay active",
    "rs1801159_TPMT / Azathioprine": "• CRITICAL: Your TPMT activity is very low — standard doses of azathioprine, 6-MP, or thioguanine can cause life-threatening bone marrow suppression\n• Your doctor must test TPMT before prescribing these drugs\n• You need a significantly reduced dose (10-20% of standard)\n· Consider alternatives: methotrexate, mycophenolate, or biologics",
    "rs1800460_TPMT / Thiopurines": "• Your TPMT activity is moderately reduced\n• If prescribed azathioprine or 6-MP, your starting dose should be reduced by ~30-50%\n• Regular blood count monitoring is important during treatment",
    "rs2066853_AHR / Detoxification": "• Eat plenty of cruciferous vegetables (broccoli, Brussels sprouts, kale, cabbage) which support AhR function\n• Minimize exposure to environmental toxins (smoke, pollution, pesticides)\n• A healthy liver supports all detox pathways — limit alcohol and processed foods",
    "rs762551_Caffeine Metabolism (CYP1A2)": "• Fast metabolizer (AA): 3-4 cups of coffee daily is safe and may even be heart-protective\n• Slow metabolizer (CC or C): limit to 1-2 cups daily — more is linked to higher heart risk and sleep disruption\n• Slow metabolizers: avoid caffeine after 2 PM to protect sleep quality\n• Decaf or half-caf options are your friend if you love coffee but are a slow metabolizer",
    "rs776746_CYP3A5 / Drug Metabolism": "• You don't produce functional CYP3A5 — about 65% of Europeans share this\n• If you need tacrolimus (transplant anti-rejection drug), you need a lower dose than African populations\n• Discuss with your doctor before starting medications that are CYP3A substrates\n• Common affected drugs: some statins, calcium channel blockers, and immunosuppressants",
    "rs4149056_Statins / SLCO1B1": "• IMPORTANT: Discuss with your doctor before starting simvastatin (Zocor)\n• You have sharply increased risk of muscle pain and rhabdomyolysis with simvastatin\n• Rosuvastatin (Crestor), pravastatin, or low-dose atorvastatin are safer alternatives\n• If you're already on a statin without side effects, you're fine — this only affects starting treatment",
    "rs12248560_CYP2C19 / Clopidogrel": "• Your body activates clopidogrel FASTER than normal — better clot prevention but higher bleeding risk\n• If prescribed clopidogrel after a stent, you're getting good protection\n• Tell your doctor before any surgery — may need to pause clopidogrel earlier\n• Watch for unusual bruising or bleeding",
    "rs4244285_CYP2C19 / Clopidogrel": "• CRITICAL: Your body CANNOT activate clopidogrel (Plavix) — it won't protect you from blood clots\n• If you have a heart stent or are at risk for stroke, clopidogrel is ineffective for you\n• Ask your doctor about alternatives: ticagrelor (Brilinta) or prasugrel (Effient)\n• Keep this result in your medical records — it could be life-saving",
    "rs4986893_CYP2C19 / Clopidogrel": "• Same as the *2 variant — clopidogrel won't work for you\n• More common in East Asian populations (up to 10% carry this)\n• Ask about ticagrelor or prasugrel as alternatives\n• Carry this information with you for medical emergencies",
    "rs7495174_Eye Color": "• This is a physical trait — no health considerations\n• Your eye color is determined by multiple genes working together\n• If you have light-colored eyes, you may be more sensitive to bright light",
    "rs12913832_Eye Color (Blue/Brown)": "• Physical trait — no health concerns\n• Light-eyed individuals may benefit from wearing sunglasses more consistently in bright conditions",
    "rs1805007_Hair Color (Red)": "• Red hair and fair skin means higher sun sensitivity — use SPF 30+ daily\n• Higher skin cancer risk — get annual skin checks with a dermatologist\n• Redheads process pain medication differently — discuss with your doctor before surgery\n• Your body produces vitamin D more efficiently from less sunlight",
    "rs1805008_Hair Color (Red)": "• Same MC1R-related advice: sun protection, skin cancer screening, and anesthesia awareness\n• Even without red hair, this variant gives you sun-sensitive skin",
    "rs1805009_Hair Color (Red)": "• Same sun safety advice as other MC1R variants\n• SPF daily, regular skin checks, and discuss anesthesia sensitivity with your doctor",
    "rs17822931_Earwax Type": "• No health concerns — this is a harmless physical trait\n• Wet earwax is more common in European and African populations\n• Dry earwax is more common in East Asian populations\n• Both types are normal — no cleaning needed beyond the outer ear",
    "rs3827760_Hair Thickness": "• Physical trait — no health implications\n• This same gene (EDAR) also influences tooth shape and sweat gland density\n• These are normal variations, not medical conditions",
    "rs16891982_Skin Pigmentation": "• Lighter skin means less natural sun protection — use SPF daily\n• Get regular skin checks if you have fair skin\n• Check your vitamin D levels — lighter skin produces it more efficiently from less sun",
    "rs1426654_Skin Pigmentation": "• Same as above — lighter pigmentation means higher sun sensitivity\n• Daily SPF and annual skin checks recommended\n• Skin cancer prevention: avoid tanning beds, seek shade during peak hours",
    "rs4988235_Lactose Tolerance": "• If you can digest milk as an adult, you carry the lactase persistence variant\n• This is a useful adaptation for dairy consumption but no special action needed\n• Dairy is a good source of calcium, protein, and vitamin D if you tolerate it well",
    "rs621922_Freckles": "• Freckles are a normal skin trait — no health concern on their own\n• People with freckles often have fairer, more sun-sensitive skin\n• Use SPF daily and get a mole check if you have many freckles or light skin",
    "rs10756819_Male Pattern Baldness": "• This is a cosmetic trait, not a health condition\n• If concerned about hair loss, options include: finasteride (oral), minoxidil (topical), low-level laser therapy\n• Starting treatment early (at first signs) gives the best results\n• Hair transplant is an option for advanced cases\n• Baldness is linked to higher androgens, which may also mean lower prostate cancer risk",
    "rs2180439_Male Pattern Baldness": "• Same advice as above — multiple genes contribute to baldness risk\n• Combining finasteride + minoxidil works better than either alone\n• Evidence-based treatments are available, but results vary",
    "rs28777_Hair Type (Straight/Curly)": "• Physical trait — no health implications\n• Hair type affects how you care for your hair (products, washing frequency) but nothing medical",
    "rs11803731_Hair Graying": "• Cosmetic trait — no health concern\n• Premature graying can be a sign of certain nutritional deficiencies (B12, copper) in rare cases\n• If graying happens very early (before 20), check B12 levels\n• Otherwise, it's just genetics — nothing wrong with gray hair",
    "rs1801133_Folate Metabolism": "• Take methylfolate (400-800 mcg) instead of regular folic acid — your body processes it better\n• Crucial during pregnancy: adequate folate prevents neural tube defects\n• Eat folate-rich foods: spinach, kale, asparagus, Brussels sprouts, beans, citrus\n• If you're trying to conceive or pregnant, discuss methylfolate with your doctor",
    "rs1801131_Folate Metabolism (A1298C)": "• Same advice as C677T but milder — methylfolate still a good choice\n• If you have both C677T and A1298C (compound heterozygote), treat it like two C677T variants\n• Consider testing homocysteine levels to assess functional impact",
    "rs762551_Caffeine Metabolism": "• Fast metabolizer (AA): coffee is healthy for you — enjoy 3-4 cups guilt-free\n• Slow metabolizer (C-carrier): limit to 1-2 cups daily\n• Slow metabolizers: caffeine after noon may disrupt sleep quality more than for fast metabolizers\n• Slow metabolizers with high coffee intake: consider decaf or switching to green tea",
    "rs705381_Vitamin B12 Levels": "• Get B12 levels tested — aim for 500-900 pg/mL range\n• Eat B12-rich foods: meat, fish, eggs, dairy, fortified nutritional yeast\n• If levels are low, sublingual B12 (methylcobalamin, 1000-2000 mcg) works well\n• Vegetarians and vegans should supplement B12 regardless of genetics",
    "rs2297518_Vitamin A / Iron": "• Eat a balanced diet rich in iron (red meat, spinach, legumes) and vitamin A (sweet potato, carrots, leafy greens)\n• If you're concerned about iron or vitamin A levels, ask your doctor for a blood test\n• No specific precautions — this variant has a mild effect on metabolism",
    "rs3750941_Iron Status": "• Your body may absorb iron more efficiently — this is usually an advantage\n• Donate blood regularly if your ferritin runs high — it's good for your health and helps others\n• Test ferritin occasionally to see where you land\n• Avoid iron supplements unless a deficiency is confirmed by blood work",
    "rs602662_Vitamin B12 Status": "• Your B12 levels tend to be above average — that's a good thing\n• Still eat B12-rich foods as part of a balanced diet\n• No special concerns — your B12 absorption works well",
    "rs12794714_Vitamin D Metabolism": "• Test your vitamin D levels — many people with this variant run low\n• Take 2000-5000 IU vitamin D3 daily depending on your blood levels\n• Get 15-20 minutes of midday sun exposure on arms and face when possible\n• Re-test after 3 months of supplementation to confirm your levels are in optimal range (50-80 ng/mL)",
    "rs1993116_Saturated Fat Sensitivity": "• Limit saturated fats: butter, fatty meats, full-fat dairy, fried foods, palm oil\n• Replace with unsaturated fats: olive oil, avocado, nuts, seeds, fatty fish\n• Your weight responds more to dietary fat composition than average\n• A Mediterranean diet (low saturated fat, high healthy fats) is ideal for you",
    "rs1535_Fatty Acid Metabolism": "• Your body converts plant-based omega-3s (ALA from flax, chia, walnuts) into EPA/DHA efficiently\n• You may benefit more from eating plant-based omega-3 sources\n• Still consider eating fatty fish (salmon, mackerel, sardines) 1-2 times per week\n· If vegetarian, ground flaxseeds and walnuts are great options",
    "rs174547_Omega-3 / Omega-6 Balance": "• Eat fatty fish 2-3x per week or take fish oil (1-2g EPA/DHA daily)\n• Reduce omega-6 heavy oils (soybean, corn, sunflower, vegetable oil blends)\n• Increase omega-3 sources: flax, chia, walnuts, hemp seeds\n• A balanced omega-6:omega-3 ratio supports healthy inflammation levels",
    "rs1784753_Sodium Sensitivity": "• Cut back on added salt — aim for less than 2,300mg sodium per day\n• Avoid processed foods (they're the biggest source of hidden sodium)\n• Use herbs, spices, lemon, or vinegar for flavor instead of salt\n• Eat potassium-rich foods (bananas, potatoes, leafy greens, yogurt) — potassium counteracts sodium\n• Monitor your blood pressure — home monitoring 1-2x per week is helpful",
    "rs5186_Salt / Blood Pressure": "• Same sodium reduction advice as the AGT variant\n• The DASH diet (rich in fruits, veggies, whole grains, low-fat dairy) is specifically proven for this variant\n• Eat foods high in potassium, magnesium, and calcium\n• Limit alcohol and exercise regularly for additional blood pressure benefits",
    "rs1799752_ACE / Blood Pressure": "• The D-allele version means higher ACE activity — your blood vessels may be tighter\n• Aerobic exercise (brisk walking, jogging, cycling, swimming) is especially beneficial\n• Watch your sodium intake and eat potassium-rich foods\n• Monitor blood pressure — home readings 1-2x per week\n• If you develop hypertension, ACE inhibitors may be particularly effective for you",
    "rs1815739_ACTN3 / Sprint Performance": "• If you have the RR or RX genotype: you have a genetic advantage for sprinting, jumping, and power activities\n• If you have the XX genotype: you lack alpha-actinin-3 but have advantages in endurance activities\n• Either way: train for YOUR goals — genetics influence the starting point, not the destination\n• XX individuals can still build strength — just with different muscle fiber recruitment",
    "rs8192678_Aerobic Fitness / PPARGC1A": "• You may need to train slightly harder or longer to see aerobic fitness gains\n• Consistency matters more than intensity for you — stick with a regular endurance program\n• HIIT may be particularly effective for overcoming this genetic limitation\n• Don't get discouraged — everyone improves with training, just at different rates",
    "rs4253778_PPARA / Endurance": "• This variant is associated with better endurance capacity\n• You may respond well to endurance training — running, cycling, swimming\n• Your body may be efficient at using fat as fuel during exercise\n• Take advantage of this — consistent endurance training will pay off",
    "rs1800795_IL-6 / Recovery": "• Your exercise recovery may be better than average\n• You may handle higher training volumes without signs of overtraining\n• Still prioritize recovery: sleep, nutrition, active recovery days\n• C-allele: lower IL-6 = potentially better recovery from intense exercise",
    "rs4646994_ACE / Endurance vs Power": "• I-allele (insertion): your body is more efficient at endurance activities\n• D-allele (deletion): your body has a power/sprint advantage\n• This is one of the most studied exercise genetics findings but training still dominates\n• Know your tendency, but train for what you enjoy most",
    "rs3764675_Muscle Mass / MSTN": "• Your myostatin levels may be slightly lower, potentially giving a slight advantage for muscle building\n• Consistent strength training is still the main driver of muscle growth\n• A protein-rich diet supports muscle protein synthesis\n• Don't expect dramatic results — this variant has a small effect compared to training",
    "rs1805086_VO2 Max / VEGFR2": "• Your blood vessels may respond well to exercise training\n• You likely have good potential to improve aerobic capacity\n• Regular endurance training (3-4x per week) will produce noticeable VO2 max gains\n• HIIT sessions once a week may accelerate improvement",
    "rs1049434_Lactate / MCT1": "• You may feel the burn (lactate accumulation) sooner during intense exercise\n• Pacing yourself is important — don't go all-out from the start\n• Consistent training improves your body's ability to clear lactate, even with this variant\n• Interval training with proper recovery periods works well for you",
    "rs2014355_Injury Risk / COL5A1": "• Pay extra attention to warm-up and cool-down before exercise\n• Incorporate Achilles tendon-specific strengthening (calf raises, eccentric heel drops)\n• Ease into new activities slowly — sudden increases in intensity raise injury risk\n• If you have Achilles pain, rest and rehab early — don't push through it\n• Consider a dynamic warm-up routine and stretching for calves and hamstrings",
    "rs12722_Tendon Injury / COL5A1": "• Your collagen structure may be more resilient — good news\n• Still follow general injury prevention: proper warm-up, progressive training load\n• Good tendon health supports lifelong mobility — don't take it for granted",
    "rs4680_COMT / Worrier vs Warrior": "• Met/Met (Worrier): You feel stress and pain more intensely — use relaxation techniques, get adequate sleep, consider magnesium or L-theanine supplements\n• Val/Val (Warrior): You handle stress well but may miss subtle body signals — practice checking in with yourself\n• Val/Met: You have a balanced COMT — the best of both worlds\n• Caffeine affects COMT types differently — worriers may be more sensitive\n• Neither type is better — different strengths for different situations",
    "rs6311_Anxiety / HTR2A": "• Your serotonin system may be more vigilant — you may notice threats and risks others miss\n• This sensitivity can be a strength in the right environment (attention to detail, cautious decision-making)\n• Manage with: regular exercise, morning sunlight, mindfulness practice, and adequate sleep\n• If anxiety affects your daily life, therapy (CBT) is very effective regardless of genetics",
    "rs25531_SERT / Stress Sensitivity": "• You may feel stress more deeply — but you also respond more positively to supportive environments\n• Building a strong support network (friends, family, therapist) is especially beneficial for you\n• Exercise, nature time, and adequate sleep help regulate stress response\n• Mindfulness meditation can retrain the stress response over time\n• If you carry the short allele, you're more responsive to both negative AND positive environments",
    "rs6265_BDNF / Neuroticism": "• Aerobic exercise is your best tool — it directly boosts BDNF and improves mood\n• Learn new things: languages, instruments, skills — novelty stimulates BDNF\n• Eat omega-3 rich foods (fatty fish, walnuts, flax) which support BDNF\n• Quality sleep is essential for BDNF-dependent brain plasticity\n• Social connection and meaningful activities support brain health",
    "rs6313_HTR2A / Personality": "• Your serotonin system influences your behavioral tendencies\n• Be aware of seasonal mood shifts and plan accordingly (light therapy, outdoor time)\n• Regular exercise and good sleep hygiene support balanced serotonin function\n• If you struggle with mood, discuss with your doctor — this variant may affect antidepressant choices",
    "rs1800497_DRD2 / Reward Seeking": "• Your brain has fewer D2 receptors — you may need more stimulation to feel satisfied\n• This can be a strength: drive, ambition, willingness to take risks\n• Watch for addictive tendencies (substances, gambling, social media, gaming)\n• Healthy dopamine sources: exercise, achievement, creative projects, social connection\n• Dopamine detox: take breaks from high-stimulation activities to reset sensitivity",
    "rs1611115_DBH / Norepinephrine": "• Your norepinephrine levels may be lower — affects attention and stress response\n• Adequate sleep, exercise, and protein intake support healthy norepinephrine levels\n• You may have a more relaxed baseline stress response\n• If you have attention difficulties, discuss with your doctor — this variant may connect to ADHD",
    "rs53576_OXTR / Empathy & Social": "• G-version: You're naturally more empathetic, trusting, and attuned to relationships\n• A-version: You may be more independent and less affected by social rejection — this isn't bad, just different\n• The G-version can mean you're more affected by social stress — build a supportive circle\n• The A-version has advantages in competitive or high-pressure environments\n• Both versions have evolutionary benefits — they're different strategies, not better or worse",
    "rs5443_GNB3 / Mood": "• Your cell signaling may affect mood regulation and antidepressant response\n• Regular exercise, sleep, and stress management are your foundation\n• If you struggle with depression or anxiety, tell your doctor about this variant — it may guide medication choice\n• T-allele carriers may respond differently to certain antidepressants (particularly SSRIs)",
    "rs324981_TAS2R38 / Bitter Taste": "• Supertaster (PAV/PAV): You're very sensitive to bitter flavors — broccoli, coffee, dark chocolate, Brussels sprouts taste extra bitter to you\n• Non-taster (AVI/AVI): You don't detect bitterness strongly — vegetables and coffee taste milder\n• Supertasters may need to work harder to eat enough vegetables — try roasting them (caramelization reduces bitterness)\n• Non-tasters may eat more vegetables but also more alcohol and fatty foods\n• This affects food preferences, not health directly — just know your taste type",
}

conn = sqlite3.connect(DB_PATH)
c = conn.cursor()

# Check for missing
c.execute("SELECT rsid, trait FROM reference_snps")
existing = {(r[0], r[1]) for r in c.fetchall()}
tip_keys = set()
for k in TIPS:
    parts = k.split("_", 1)
    tip_keys.add((parts[0], parts[1] if len(parts) > 1 else ""))

missing_from_db = tip_keys - existing
extra_in_db = existing - tip_keys

if missing_from_db:
    print(f"WARNING: {len(missing_from_db)} tips have no matching DB entry:")
    for r in missing_from_db:
        print(f"  {r[0]} - {r[1]}")

if extra_in_db:
    print(f"WARNING: {len(extra_in_db)} DB entries have no tips:")
    for r in sorted(extra_in_db):
        print(f"  {r[0]} - {r[1]}")

# Update
updated = 0
for key, tips in TIPS.items():
    parts = key.split("_", 1)
    rsid = parts[0]
    trait = parts[1] if len(parts) > 1 else ""
    c.execute("UPDATE reference_snps SET health_tips = ? WHERE rsid = ? AND trait = ?", (tips, rsid, trait))
    if c.rowcount > 0:
        updated += 1

conn.commit()
print(f"\nUpdated {updated} out of {len(TIPS)} entries with health tips")
conn.close()
